server:
  port: 8087

spring:
  application:
    name: incident-service

  datasource:
    url: jdbc:postgresql://localhost:5433/fleettrack
    username: fleettrack
    password: fleettrack

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: incident
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    schemas: incident
    default-schema: incident
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: fleettrack
    password: fleettrack

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

internal:
  service:
    secret: ${INTERNAL_SERVICE_SECRET:fleettrack-internal-dev-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
